# Generated by Django 4.2.7 on 2024-09-23 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='car',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='main.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='main.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
